version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dana080603
      POSTGRES_DB: DanaPR
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: my_python_app
    ports:
      - "5000:5000"
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata: